export const ChannelData = [

    {   id: "1",
        nom: "Pikachu",
        img: "https://tse1.mm.bing.net/th?id=OIP.hdMD2OsVbFPLpR_BLJtAdgHaHa&pid=Api",
        jeux: "Pokémon Bleu",
        titreLive: "Let's play pokémon bleu",
        nbreViews: "5,6",
},
{       id: "2",
        nom: "Alex",
        img: "https://tse1.mm.bing.net/th?id=OIP.maYFU_szG4SnFbu2CRubxwHaHs&pid=Api",
        jeux: "Call of Duty",
        titreLive: "Road to 10 Nukes",
        nbreViews: "2,3",
},
{       id: "3",
        nom: "Yami Yugi",
        img: "https://tse2.mm.bing.net/th?id=OIP.P-5xKI2KbXDGpVQtVNc5ogHaHa&pid=Api",
        jeux: "YU-GI-OH TCG",
        titreLive: "Let's go platine rank",
        nbreViews: "1,1",
},
{       id: "4",
        nom: "The VioletOne",
        img: "https://tse3.mm.bing.net/th?id=OIP.Nkm6DgiQfsTIEwREzOld8wHaHW&pid=Api",
        jeux: "My little pony",
        titreLive: "Visiting the pony city",
        nbreViews: "10,7",
},
{       id: "5",
        nom: "Vera",
        img: "https://tse3.mm.bing.net/th?id=OIP.FzUXCR9ITGNK_z2MgGICDQHaFj&pid=Api",
        jeux: "Chess",
        titreLive: "Trainning championship",
        nbreViews: "8,9",
},
{       id: "6",
        nom: "Duolingo",
        img: "https://tse3.mm.bing.net/th?id=OIP.CjXAbP_xKRBAp9vMIz6RmgHaHa&pid=Api",
        jeux: "Learning",
        titreLive: "Learn Spanish in a funny way",
        nbreViews: "1,4",
},
]
